global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Drawing;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using Microsoft.Win32;
global using System.Runtime.InteropServices.ComTypes;
global using System.Diagnostics;
global using SolidEdgeFramework;
global using SeApp = SolidEdgeFramework.Application;
global using SeDocument = SolidEdgeFramework.SolidEdgeDocument;
global using SeAssembly = SolidEdgeAssembly.AssemblyDocument;
global using SePart = SolidEdgePart.PartDocument;
global using SeSheetMetal = SolidEdgePart.SheetMetalDocument;
global using SeOccurrences = SolidEdgeAssembly.Occurrences;
global using SeOccurrence = SolidEdgeAssembly.Occurrence;
global using SeFlatPatternModels = SolidEdgePart.FlatPatternModels;
global using SeFlanges = SolidEdgePart.Flanges;
global using SeDocuments = SolidEdgeFramework.Documents;
global using SeFilePropertySets = SolidEdgeFileProperties.PropertySets;
global using SeFileProperties = SolidEdgeFileProperties.Properties;
global using SeFileProperty = SolidEdgeFileProperties.Property;
global using SePropertySets = SolidEdgeFramework.PropertySets;
global using SeProperties = SolidEdgeFramework.Properties;
global using SeProperty = SolidEdgeFramework.Property;
